# Generated by Django 3.2.5 on 2021-07-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameEngine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='current_turn',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='settings',
            name='step_size',
            field=models.IntegerField(default=1),
        ),
    ]
