# Generated by Django 3.2.5 on 2021-08-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameEngine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='start_date',
        ),
        migrations.AddField(
            model_name='gamestate',
            name='current_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='anonymous', max_length=200),
        ),
    ]
