# Generated by Django 3.2.5 on 2021-07-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='n_dead',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='n_ill',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='n_infected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='n_recovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='n_total',
            field=models.IntegerField(default=0),
        ),
    ]
